services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    env_file:
      - path: .env.app
        required: false
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - infra-net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:

networks:
  infra-net:
    external: true
    name: infra-net
