services:
  redis:
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ""
    command: redis-server --appendonly yes
    networks:
      - infra-net

networks:
  infra-net:
    driver: bridge
